name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build /Hands-on lab/lab-files/developer/content-web/ --file Dockerfile --tag test:$(date +%s)
    - name: login to acr
      run: az acr login --name techlunchdemo
    - name: upload  
      run: docker push techlunchdemo.azurecr.io/test:$(date +%s)
